import "./globals.css";
import { Providers } from "@/GlobalState/Providers";
export const metadata = {
  title: "Auth-next-template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
